### PR TITLE
Added Some Essential Plugins and Redid files

### PR DESCRIPTION
**Pull request by josephworks**

### CODE REVIEW

**Comment by sameer** [comment]
Hi @josephworks, thank you for your contribution. It's been a few years, but I will try to review this.
- Why did you move `minecraft_server.1.7.10.jar --> Thermos.jar`? Those two are separate and supposed to be different if I recall correctly.
- The .yml files were deleted, are those typically generated on first run?
- Are the kolboke and vecmath libraries no longer needed?

**Comment by josephworks** [comment]
Ok I fixed all of the problems.
The server started up gracefully.

**Comment by josephworks** [comment]
The jar needs to be thermos.jar the minecraft.jar will just start vanilla

**Comment by josephworks** [comment]
I am not sure about the two libraries, but I think I fixed the issue.

**Comment by josephworks** [comment]
@sameer what do you think of the changes?

**Comment by josephworks** [comment]
Bump

**Comment by sameer** [comment]
> The jar needs to be thermos.jar the minecraft.jar will just start vanilla

Yes, you are supposed to get the thermos.jar from CyberdyneCC/Thermos, because the version may change. The files here are supposed to be the configuration around Thermos.

**Comment by sameer** [comment]
> I am not sure about the two libraries, but I think I fixed the issue.

They may be needed for some mods, it's probably better to keep them.

**Comment by josephworks** [comment]
The files will auto generate on server start.

Joseph R.

**Comment by josephworks** [comment]
I tested the server before I bumped this thread, and the server worked great.

**Comment by josephworks** [comment]
Have you tried starting the server with my changes yet?

**Comment by josephworks** [comment]
bump*

**Comment by josephworks** [comment]
bump

**Comment by josephworks** [comment]
@sameer have you tried my changes yet. I would like to finish the merge so I can remove the fork from my account...

**Comment by Grand-Trizmo** [comment]
why are we adding random plugins in 
server owners can choose what plugins they want themselves.

**Comment by Time6628** [comment]
This does work, but it would be better to no redistribute other people's plugins. It would also be best to let other's use what plugins they want. Most of those files are essential as well, so the server doesn't have to generate them when they start the server for the first.

**Pull request closed without merging**
